load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "endianness",
    srcs = [
        "endianness.c",
        "endianness.h",
    ],
    hdrs = [
        "endianness.h",
    ],
)